channel: '#APP_NAME'

application: previousnext/lamp:latest

prepare: &prepare
  - git config --global user.email "${GIT_EMAIL}" && git config --global user.name "${GIT_USER}"
  - make init-ci
  - make mkdirs
  - make styleguide
  - cp app/sites/default/test.settings.php app/sites/default/settings.test.php

test: &test
  - make check-expire
  - make ci-lint-php
  - make lint-sass-js
  - make build
  - make ci-test

test_pr:
  setup: *prepare
  steps: *test

test_head:
  setup: *prepare
  steps: *test

patch:
  steps:
    - sh scripts/patchy.sh

config:
  variables:
    - "YARN_CACHE_FOLDER=/var/tmp/yarn"
