cluster: "pnx.cd.pnx.com.au"

channel: '#APP_NAME'

package:
  image: previousnext/php-apache:7.2-3.x-dev
  steps: []

deploySteps:
  - make deploy

# A list of all environment configuration.
environments:
  - name: "dev"
    spec:
      domain:
        - "APP_NAME-qa.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      mounts: *mounts
      jobs:   *jobs
  - name: "staging"
    spec:
      domain:
        - "APP_NAME-staging.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      mounts: *mounts
      jobs:   *jobs
  - name: "prod"
    spec:
      domain:
        - "APP_NAME-prod.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      minInstances: 2
      maxMemory:    512
      mounts:       *mounts
      jobs:         *jobs

# Standard mount configuration for all environments.
mounts: &mounts
  - name: "public"
    path: "/data/app/sites/default/files"
    beta: true
  - name: "private"
    path: "/private"
    beta: true

# Standard cron runs for all environments.
jobs: &jobs
  - name:       "drush"
    workingDir: "/data/app"
    schedule:   "@hourly"
    command:    "drush cron"
