cluster: "pnx.cd.pnx.com.au"

channel: '#APP_NAME'

package:
  steps:
    - "composer install --no-dev --prefer-dist --no-progress --optimize-autoloader"
    - "npm install --loglevel silent &> /tmp/npminstall.log"
    - "node_modules/.bin/gulp build"

deploySteps:
  - make deploy

# A list of all environment configuration.
environments:
  - name: "dev"
    spec:
      domain:
        - "APP_NAME-qa.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      mounts: *mounts
      jobs:   *jobs
  - name: "staging"
    spec:
      domain:
        - "APP_NAME-staging.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      mounts: *mounts
      jobs:   *jobs
  - name: "prod"
    spec:
      domain:
        - "APP_NAME-prod.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      minInstances: 2
      maxMemory:    512
      mounts:       *mounts
      jobs:         *jobs

# Standard mount configuration for all environments.
mounts: &mounts
  - name: "public"
    path: "/data/app/sites/default/files"
    beta: true
  - name: "private"
    path: "/private"
    beta: true

# Standard cron runs for all environments.
jobs: &jobs
  - name:       "drush"
    workingDir: "/data/app"
    schedule:   "0 * * * *"
    command:    "drush cron"
  - name:       "backup"
    workingDir: "/data/app"
    schedule:   "0 0 * * *"
    command:    'drush archive-dump --overwrite --destination=/tmp/drupal.tar.gz && backup /tmp/drupal.tar.gz pnx-backups "APP_NAME/%FREQUENCY%/%TIMESTAMP%-$SKIPPER_ENV.tar.gz"'

