cluster: "pnx.cd.pnx.com.au"

channel: '#APP_NAME'

package:
  image: previousnext/php:7.1-dev
  steps:
    - make init-package
    - make styleguide

deploySteps:
  - make deploy

# A list of all environment configuration.
environments:
  - name: "dev"
    spec:
      domain:
        - "APP_NAME-qa.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      mounts: *mounts
      jobs:   *jobs
  - name: "staging"
    spec:
      domain:
        - "APP_NAME-staging.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      mounts: *mounts
      jobs:   *jobs
  - name: "prod"
    spec:
      domain:
        - "APP_NAME-prod.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      minInstances: 2
      maxMemory:    512
      mounts:       *mounts
      jobs:         *jobs

# Standard mount configuration for all environments.
mounts: &mounts
  - name: "public"
    path: "/data/app/sites/default/files"
    beta: true
  - name: "private"
    path: "/private"
    beta: true

# Standard cron runs for all environments.
jobs: &jobs
  - name:       "drush"
    workingDir: "/data/app"
    schedule:   "@hourly"
    command:    "drush cron"

  - name:       "backup-db"
    workingDir: "/data/app"
    schedule:   "@daily"
    command:    |
      drush sql-dump --structure-tables-key=common > /tmp/db.sql && \
      tar -zcvf /tmp/db.tar.gz /tmp/db.sql && \
      backup /tmp/db.tar.gz pnx-backups "%FREQUENCY%/APP_NAME/%TIMESTAMP%-$SKIPPER_ENV-db.tar.gz"
    minCPU:     100

  - name:       "backup-mount-public"
    workingDir: "/data/app/sites/default/files"
    schedule:   "@daily"
    command:    |
      tar -czf /tmp/files-public.tar.gz \
        --exclude=css \
        --exclude=js \
        --exclude=styles \
        --exclude=xmlsitemap \
        . && \
      backup /tmp/files-public.tar.gz pnx-backups "APP_NAME/%FREQUENCY%/%TIMESTAMP%-$SKIPPER_ENV-files-public.tar.gz"
    minCPU:     100

  - name:       "backup-mount-private"
    workingDir: "/private"
    schedule:   "@daily"
    command:    |
      tar -czf /tmp/files-private.tar.gz . && \
      backup /tmp/files-private.tar.gz pnx-backups "APP_NAME/%FREQUENCY%/%TIMESTAMP%-$SKIPPER_ENV-files-private.tar.gz"
    minCPU:     100
