cluster: "pnx.cd.pnx.com.au"

channel: '#APP_NAME'

package:
  image: previousnext/php:7.0-dev
  steps:
    - make init-package
    - make styleguide

deploySteps:
  - make deploy

# A list of all environment configuration.
environments:
  - name: "dev"
    spec:
      domain:
        - "APP_NAME-qa.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      mounts: *mounts
      jobs:   *jobs
  - name: "staging"
    spec:
      domain:
        - "APP_NAME-staging.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      mounts: *mounts
      jobs:   *jobs
  - name: "prod"
    spec:
      domain:
        - "APP_NAME-prod.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      minInstances: 2
      maxMemory:    512
      mounts:       *mounts
      jobs:         *jobs

# Standard mount configuration for all environments.
mounts: &mounts
  - name: "public"
    path: "/data/app/sites/default/files"
    beta: true
  - name: "private"
    path: "/private"
    beta: true

# Standard cron runs for all environments.
jobs: &jobs
  - name:       "drush"
    workingDir: "/data/app"
    schedule:   "@hourly"
    command:    "drush cron"

  - name:       "backup-db"
    workingDir: "/data/app"
    schedule:   "@daily"
    command:    |
      mysqldump --user=$(cat /etc/skpr/mysql.db.user) --password=$(cat /etc/skpr/mysql.db.pass) --host=$(cat /etc/skpr/mysql.db.host) $(cat /etc/skpr/mysql.db.name) --single-transaction --quick > /tmp/db.sql && \
      tar -zcvf /tmp/db.tar.gz /tmp/db.sql && \
      backup /tmp/db.tar.gz pnx-backups "%FREQUENCY%/APP_NAME/%TIMESTAMP%-$SKIPPER_ENV-db.tar.gz"
    minCPU:     100

  - name:       "backup-files"
    workingDir: "/data/app"
    schedule:   "@daily"
    command:    'tar -czf /tmp/files.tar.gz /data/app/sites/default/files /private && backup /tmp/files.tar.gz pnx-backups "APP_NAME/%FREQUENCY%/%TIMESTAMP%-$SKIPPER_ENV-files.tar.gz"'
    minCPU:     100
