version: "3"
services:
  php:
    image: previousnext/php:7.1-dev
    ports:
      - "80:80"
    volumes:
      - .:/data:cached
    links:
      - db
      - mail
#      - search
    environment:
      - SIMPLETEST_BASE_URL=http://php
      - SIMPLETEST_DB=mysql://root:root@db/d8_testing
  xdebug:
    image: nickschuch/d4m-tcp-forwarder
    network_mode: host
    environment:
      - PORT=9000
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      # Required for running the official mysql image.
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    #    volumes:
    #      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql or sql.gz file(s) here.
  mail:
    image: mailhog/mailhog
    ports:
      - "8002:8025"

#  search:
#    image: previousnext/solr
#    ports:
#      - "8983:8983"
