# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
# Environment variables:
# Most environment variables are set at the org level. You need to explicitly
# set the following per project:
#   - SLACK_WEBHOOK_URL
#
version: 2
jobs:

  # Run the build and test steps.
  build_and_test:
    docker:
      - image: previousnext/php:7.2-dev
        environment:
          # Load nvm in each run command.
          BASH_ENV: ~/.bashrc

    working_directory: /data

    steps:
      - checkout

      - restore_cache:
          keys:
            - pnx-project-v1-{{ arch }}

      - run:
          name: "Install dependencies"
          command: |
            make ci-init

      - save_cache:
          key: pnx-project-v1-{{ arch }}
          paths:
            - /root/.composer
            - /usr/local/share/.cache/yarn

      - run:
          name: Lint
          command: |
            make ci-lint-php
            make lint-sass-js

      - run:
          name: Styleguide
          command: |
            make styleguide

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test:
          context: org-global
